/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as QuizzesRouteImport } from './routes/quizzes'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PeersRouteImport } from './routes/peers'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForumRouteImport } from './routes/forum'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CompetitionsRouteImport } from './routes/competitions'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminTeachersRouteImport } from './routes/admin/teachers'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminTeachersTeacherIdRouteImport } from './routes/admin/teachers.$teacherId'
import { Route as AdminStudentsStudentIdRouteImport } from './routes/admin/students.$studentId'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesRoute = QuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PeersRoute = PeersRouteImport.update({
  id: '/peers',
  path: '/peers',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumRoute = ForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsRoute = CompetitionsRouteImport.update({
  id: '/competitions',
  path: '/competitions',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeachersRoute = AdminTeachersRouteImport.update({
  id: '/admin/teachers',
  path: '/admin/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeachersTeacherIdRoute = AdminTeachersTeacherIdRouteImport.update({
  id: '/$teacherId',
  path: '/$teacherId',
  getParentRoute: () => AdminTeachersRoute,
} as any)
const AdminStudentsStudentIdRoute = AdminStudentsStudentIdRouteImport.update({
  id: '/admin/students/$studentId',
  path: '/admin/students/$studentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chat': typeof ChatRoute
  '/competitions': typeof CompetitionsRoute
  '/dashboard': typeof DashboardRoute
  '/forum': typeof ForumRoute
  '/login': typeof LoginRoute
  '/peers': typeof PeersRoute
  '/portal': typeof PortalRoute
  '/quizzes': typeof QuizzesRoute
  '/resources': typeof ResourcesRoute
  '/simulator': typeof SimulatorRoute
  '/tasks': typeof TasksRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/teachers': typeof AdminTeachersRouteWithChildren
  '/admin/students/$studentId': typeof AdminStudentsStudentIdRoute
  '/admin/teachers/$teacherId': typeof AdminTeachersTeacherIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chat': typeof ChatRoute
  '/competitions': typeof CompetitionsRoute
  '/dashboard': typeof DashboardRoute
  '/forum': typeof ForumRoute
  '/login': typeof LoginRoute
  '/peers': typeof PeersRoute
  '/portal': typeof PortalRoute
  '/quizzes': typeof QuizzesRoute
  '/resources': typeof ResourcesRoute
  '/simulator': typeof SimulatorRoute
  '/tasks': typeof TasksRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/teachers': typeof AdminTeachersRouteWithChildren
  '/admin/students/$studentId': typeof AdminStudentsStudentIdRoute
  '/admin/teachers/$teacherId': typeof AdminTeachersTeacherIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chat': typeof ChatRoute
  '/competitions': typeof CompetitionsRoute
  '/dashboard': typeof DashboardRoute
  '/forum': typeof ForumRoute
  '/login': typeof LoginRoute
  '/peers': typeof PeersRoute
  '/portal': typeof PortalRoute
  '/quizzes': typeof QuizzesRoute
  '/resources': typeof ResourcesRoute
  '/simulator': typeof SimulatorRoute
  '/tasks': typeof TasksRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/teachers': typeof AdminTeachersRouteWithChildren
  '/admin/students/$studentId': typeof AdminStudentsStudentIdRoute
  '/admin/teachers/$teacherId': typeof AdminTeachersTeacherIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/chat'
    | '/competitions'
    | '/dashboard'
    | '/forum'
    | '/login'
    | '/peers'
    | '/portal'
    | '/quizzes'
    | '/resources'
    | '/simulator'
    | '/tasks'
    | '/admin/dashboard'
    | '/admin/teachers'
    | '/admin/students/$studentId'
    | '/admin/teachers/$teacherId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/chat'
    | '/competitions'
    | '/dashboard'
    | '/forum'
    | '/login'
    | '/peers'
    | '/portal'
    | '/quizzes'
    | '/resources'
    | '/simulator'
    | '/tasks'
    | '/admin/dashboard'
    | '/admin/teachers'
    | '/admin/students/$studentId'
    | '/admin/teachers/$teacherId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/chat'
    | '/competitions'
    | '/dashboard'
    | '/forum'
    | '/login'
    | '/peers'
    | '/portal'
    | '/quizzes'
    | '/resources'
    | '/simulator'
    | '/tasks'
    | '/admin/dashboard'
    | '/admin/teachers'
    | '/admin/students/$studentId'
    | '/admin/teachers/$teacherId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ChatRoute: typeof ChatRoute
  CompetitionsRoute: typeof CompetitionsRoute
  DashboardRoute: typeof DashboardRoute
  ForumRoute: typeof ForumRoute
  LoginRoute: typeof LoginRoute
  PeersRoute: typeof PeersRoute
  PortalRoute: typeof PortalRoute
  QuizzesRoute: typeof QuizzesRoute
  ResourcesRoute: typeof ResourcesRoute
  SimulatorRoute: typeof SimulatorRoute
  TasksRoute: typeof TasksRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminTeachersRoute: typeof AdminTeachersRouteWithChildren
  AdminStudentsStudentIdRoute: typeof AdminStudentsStudentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes': {
      id: '/quizzes'
      path: '/quizzes'
      fullPath: '/quizzes'
      preLoaderRoute: typeof QuizzesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peers': {
      id: '/peers'
      path: '/peers'
      fullPath: '/peers'
      preLoaderRoute: typeof PeersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum': {
      id: '/forum'
      path: '/forum'
      fullPath: '/forum'
      preLoaderRoute: typeof ForumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions': {
      id: '/competitions'
      path: '/competitions'
      fullPath: '/competitions'
      preLoaderRoute: typeof CompetitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/teachers': {
      id: '/admin/teachers'
      path: '/admin/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AdminTeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/teachers/$teacherId': {
      id: '/admin/teachers/$teacherId'
      path: '/$teacherId'
      fullPath: '/admin/teachers/$teacherId'
      preLoaderRoute: typeof AdminTeachersTeacherIdRouteImport
      parentRoute: typeof AdminTeachersRoute
    }
    '/admin/students/$studentId': {
      id: '/admin/students/$studentId'
      path: '/admin/students/$studentId'
      fullPath: '/admin/students/$studentId'
      preLoaderRoute: typeof AdminStudentsStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminTeachersRouteChildren {
  AdminTeachersTeacherIdRoute: typeof AdminTeachersTeacherIdRoute
}

const AdminTeachersRouteChildren: AdminTeachersRouteChildren = {
  AdminTeachersTeacherIdRoute: AdminTeachersTeacherIdRoute,
}

const AdminTeachersRouteWithChildren = AdminTeachersRoute._addFileChildren(
  AdminTeachersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ChatRoute: ChatRoute,
  CompetitionsRoute: CompetitionsRoute,
  DashboardRoute: DashboardRoute,
  ForumRoute: ForumRoute,
  LoginRoute: LoginRoute,
  PeersRoute: PeersRoute,
  PortalRoute: PortalRoute,
  QuizzesRoute: QuizzesRoute,
  ResourcesRoute: ResourcesRoute,
  SimulatorRoute: SimulatorRoute,
  TasksRoute: TasksRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminTeachersRoute: AdminTeachersRouteWithChildren,
  AdminStudentsStudentIdRoute: AdminStudentsStudentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
