"""add_phone_to_students

Revision ID: 3c54831bebab
Revises: 
Create Date: 2026-03-10 20:59:10.754703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3c54831bebab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('phone', sa.String(length=30), nullable=True))
    op.drop_column('students', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('role', mysql.ENUM('STUDENT', 'ADVISOR', 'ADMIN'), nullable=False))
    op.drop_column('students', 'phone')
    # ### end Alembic commands ###
