"""quiz_teacher_fk_and_assigned_dept

Revision ID: 839dde5f3fe7
Revises: f2ffb28c05c0
Create Date: 2026-03-10 23:26:06.369586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '839dde5f3fe7'
down_revision: Union[str, Sequence[str], None] = 'f2ffb28c05c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('assigned_department', sa.String(length=120), nullable=True))
    op.drop_constraint(op.f('quizzes_ibfk_2'), 'quizzes', type_='foreignkey')
    op.create_foreign_key(None, 'quizzes', 'teachers', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.create_foreign_key(op.f('quizzes_ibfk_2'), 'quizzes', 'students', ['created_by'], ['id'])
    op.drop_column('quizzes', 'assigned_department')
    # ### end Alembic commands ###
