"""replace_cohort_with_dept_section_batch

Revision ID: f2ffb28c05c0
Revises: 3c54831bebab
Create Date: 2026-03-10 22:36:03.182841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f2ffb28c05c0'
down_revision: Union[str, Sequence[str], None] = '3c54831bebab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('department', sa.String(length=120), nullable=True))
    op.add_column('students', sa.Column('section', sa.String(length=60), nullable=True))
    op.add_column('students', sa.Column('batch_start_year', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('batch_end_year', sa.Integer(), nullable=True))
    op.drop_column('students', 'cohort')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('cohort', mysql.VARCHAR(length=60), nullable=True))
    op.drop_column('students', 'batch_end_year')
    op.drop_column('students', 'batch_start_year')
    op.drop_column('students', 'section')
    op.drop_column('students', 'department')
    # ### end Alembic commands ###
